name: CD Pipeline - Deploy to Production

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to FTP Server
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite

    - name: Install production dependencies
      run: composer install --no-dev --optimize-autoloader --no-progress

    - name: Warmup cache
      run: |
        php bin/console cache:clear --env=prod --no-debug
        php bin/console cache:warmup --env=prod --no-debug

    - name: Optimize for production
      run: |
        rm -rf var/cache/dev
        rm -rf var/log/dev.log
        rm -rf tests/
        rm -f .env.local
        rm -f .env.test
        rm -f phpunit.xml
        rm -rf .git/

    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        local-dir: ./
        server-dir: /public_html/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/tests/**
          **/.env.local
          **/.env.test
          **/var/cache/dev/**
          **/var/log/**
          README.md
          phpunit.xml

    - name: Post-deployment setup
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        script: |
          cd public_html
          php bin/console doctrine:database:create --if-not-exists --env=prod
          php bin/console doctrine:migrations:migrate --no-interaction --env=prod
          # php bin/console doctrine:fixtures:load --no-interaction --env=prod
          chmod -R 755 var/
          chmod -R 755 public/
